# Generated by Django 6.0 on 2025-12-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvite',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
